namespace ExoticStudio.UserControls
{
    partial class FrequencyGraph
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this._graph = new NPlot.Windows.PlotSurface2D();
            this.SuspendLayout();
            // 
            // _graph
            // 
            this._graph.AutoScaleAutoGeneratedAxes = false;
            this._graph.AutoScaleTitle = false;
            this._graph.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this._graph.DateTimeToolTip = false;
            this._graph.Dock = System.Windows.Forms.DockStyle.Fill;
            this._graph.Legend = null;
            this._graph.LegendZOrder = -1;
            this._graph.Location = new System.Drawing.Point(0, 0);
            this._graph.Name = "_graph";
            this._graph.RightMenu = null;
            this._graph.ShowCoordinates = true;
            this._graph.Size = new System.Drawing.Size(150, 150);
            this._graph.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
            this._graph.TabIndex = 0;
            this._graph.Text = "plotSurface2D1";
            this._graph.Title = "";
            this._graph.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this._graph.XAxis1 = null;
            this._graph.XAxis2 = null;
            this._graph.YAxis1 = null;
            this._graph.YAxis2 = null;
            
            // 
            // FrequencyGraph
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this._graph);
            this.Name = "FrequencyGraph";
            
            this.ResumeLayout(false);

        }

        #endregion

        private NPlot.Windows.PlotSurface2D _graph;
    }
}
