namespace OddsEditor.MyComponents
{
    partial class BackTestControl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            this.label1 = new System.Windows.Forms.Label();
            this._txtboxConstant = new System.Windows.Forms.TextBox();
            this._grid = new System.Windows.Forms.DataGridView();
            this._buttonGo = new System.Windows.Forms.Button();
            this._txtboxOutput = new System.Windows.Forms.TextBox();
            this._graphNumberOfContenders = new NPlot.Windows.PlotSurface2D();
            this._grapWinningPercentages = new NPlot.Windows.PlotSurface2D();
            ((System.ComponentModel.ISupportInitialize)(this._grid)).BeginInit();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(13, 14);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(49, 13);
            this.label1.TabIndex = 0;
            this.label1.Text = "Constant";
            // 
            // _txtboxConstant
            // 
            this._txtboxConstant.Location = new System.Drawing.Point(82, 14);
            this._txtboxConstant.Name = "_txtboxConstant";
            this._txtboxConstant.Size = new System.Drawing.Size(36, 20);
            this._txtboxConstant.TabIndex = 1;
            this._txtboxConstant.Text = "18";
            // 
            // _grid
            // 
            this._grid.AllowUserToAddRows = false;
            this._grid.AllowUserToDeleteRows = false;
            this._grid.AllowUserToResizeColumns = false;
            this._grid.AllowUserToResizeRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.Gainsboro;
            this._grid.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this._grid.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)));
            this._grid.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.AllCells;
            this._grid.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this._grid.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.None;
            this._grid.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this._grid.Location = new System.Drawing.Point(3, 86);
            this._grid.Name = "_grid";
            this._grid.RowHeadersVisible = false;
            this._grid.Size = new System.Drawing.Size(335, 501);
            this._grid.TabIndex = 2;
            // 
            // _buttonGo
            // 
            this._buttonGo.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this._buttonGo.Location = new System.Drawing.Point(797, 4);
            this._buttonGo.Name = "_buttonGo";
            this._buttonGo.Size = new System.Drawing.Size(75, 39);
            this._buttonGo.TabIndex = 3;
            this._buttonGo.Text = "Go";
            this._buttonGo.UseVisualStyleBackColor = true;
            this._buttonGo.Click += new System.EventHandler(this.OnGo);
            // 
            // _txtboxOutput
            // 
            this._txtboxOutput.Location = new System.Drawing.Point(16, 44);
            this._txtboxOutput.Multiline = true;
            this._txtboxOutput.Name = "_txtboxOutput";
            this._txtboxOutput.ReadOnly = true;
            this._txtboxOutput.Size = new System.Drawing.Size(238, 36);
            this._txtboxOutput.TabIndex = 4;
            // 
            // _graphNumberOfContenders
            // 
            this._graphNumberOfContenders.AutoScaleAutoGeneratedAxes = false;
            this._graphNumberOfContenders.AutoScaleTitle = false;
            this._graphNumberOfContenders.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this._graphNumberOfContenders.DateTimeToolTip = false;
            this._graphNumberOfContenders.Legend = null;
            this._graphNumberOfContenders.LegendZOrder = -1;
            this._graphNumberOfContenders.Location = new System.Drawing.Point(372, 86);
            this._graphNumberOfContenders.Name = "_graphNumberOfContenders";
            this._graphNumberOfContenders.RightMenu = null;
            this._graphNumberOfContenders.ShowCoordinates = true;
            this._graphNumberOfContenders.Size = new System.Drawing.Size(374, 216);
            this._graphNumberOfContenders.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
            this._graphNumberOfContenders.TabIndex = 5;
            this._graphNumberOfContenders.Text = "plotSurface2D1";
            this._graphNumberOfContenders.Title = "";
            this._graphNumberOfContenders.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this._graphNumberOfContenders.XAxis1 = null;
            this._graphNumberOfContenders.XAxis2 = null;
            this._graphNumberOfContenders.YAxis1 = null;
            this._graphNumberOfContenders.YAxis2 = null;
            // 
            // _grapWinningPercentages
            // 
            this._grapWinningPercentages.AutoScaleAutoGeneratedAxes = false;
            this._grapWinningPercentages.AutoScaleTitle = false;
            this._grapWinningPercentages.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this._grapWinningPercentages.DateTimeToolTip = false;
            this._grapWinningPercentages.Legend = null;
            this._grapWinningPercentages.LegendZOrder = -1;
            this._grapWinningPercentages.Location = new System.Drawing.Point(372, 342);
            this._grapWinningPercentages.Name = "_grapWinningPercentages";
            this._grapWinningPercentages.RightMenu = null;
            this._grapWinningPercentages.ShowCoordinates = true;
            this._grapWinningPercentages.Size = new System.Drawing.Size(374, 216);
            this._grapWinningPercentages.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.None;
            this._grapWinningPercentages.TabIndex = 6;
            this._grapWinningPercentages.Text = "plotSurface2D1";
            this._grapWinningPercentages.Title = "";
            this._grapWinningPercentages.TitleFont = new System.Drawing.Font("Arial", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this._grapWinningPercentages.XAxis1 = null;
            this._grapWinningPercentages.XAxis2 = null;
            this._grapWinningPercentages.YAxis1 = null;
            this._grapWinningPercentages.YAxis2 = null;
            // 
            // BackTestControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this._grapWinningPercentages);
            this.Controls.Add(this._graphNumberOfContenders);
            this.Controls.Add(this._txtboxOutput);
            this.Controls.Add(this._buttonGo);
            this.Controls.Add(this._grid);
            this.Controls.Add(this._txtboxConstant);
            this.Controls.Add(this.label1);
            this.Name = "BackTestControl";
            this.Size = new System.Drawing.Size(889, 593);
            ((System.ComponentModel.ISupportInitialize)(this._grid)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox _txtboxConstant;
        private System.Windows.Forms.DataGridView _grid;
        private System.Windows.Forms.Button _buttonGo;
        private System.Windows.Forms.TextBox _txtboxOutput;
        private NPlot.Windows.PlotSurface2D _graphNumberOfContenders;
        private NPlot.Windows.PlotSurface2D _grapWinningPercentages;
    }
}
